In [21]:
import pandas as pd

In [4]:
#leer archivo cv de un website 
df_premier=pd.read_csv('https://www.football-data.co.uk/mmz4281/2021/E0.csv')

In [5]:
df_premier

,Div,Date,Time,HomeTeam,AwayTeam,FTHG,FTAG,FTR,HTHG,HTAG,...,AvgC<2.5,AHCh,B365CAHH,B365CAHA,PCAHH,PCAHA,MaxCAHH,MaxCAHA,AvgCAHH,AvgCAHA
0,E0,12/09/2020,12:30,Fulham,Arsenal,0,3,A,0,1,...,1.84,0.75,2.01,1.89,2.02,1.91,2.13,1.92,2.02,1.87
1,E0,12/09/2020,15:00,Crystal Palace,Southampton,1,0,H,1,0,...,1.70,0.25,1.78,2.13,1.79,2.17,1.85,2.18,1.79,2.12
2,E0,12/09/2020,17:30,Liverpool,Leeds,4,3,H,3,2,...,2.62,-1.50,1.85,2.05,1.85,2.08,1.90,2.16,1.84,2.04
3,E0,12/09/2020,20:00,West Ham,Newcastle,0,2,A,0,0,...,1.92,-0.50,2.03,1.87,2.04,1.88,2.09,1.91,2.02,1.86
4,E0,13/09/2020,14:00,West Brom,Leicester,0,3,A,0,0,...,1.73,0.25,1.92,1.98,1.93,1.99,1.95,2.01,1.91,1.97
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
375,E0,23/05/2021,16:00,Liverpool,Crystal Palace,2,0,H,1,0,...,3.49,-2.25,1.86,2.04,1.88,2.03,1.98,2.14,1.88,2.00
376,E0,23/05/2021,16:00,Man City,Everton,5,0,H,2,0,...,2.77,-1.75,2.01,1.89,1.99,1.89,2.20,2.00,2.03,1.85
377,E0,23/05/2021,16:00,Sheffield United,Burnley,1,0,H,1,0,...,2.05,0.00,2.04,1.86,2.05,1.86,2.17,1.90,2.03,1.84
378,E0,23/05/2021,16:00,West Ham,Southampton,3,0,H,2,0,...,2.14,-0.75,2.00,1.90,2.02,1.91,2.06,2.01,1.99,1.89
379,E0,23/05/2021,16:00,Wolves,Man United,1,2,A,1,2,...,1.62,-0.25,2.04,1.86,2.10,1.84,2.10,1.94,2.00,1.88

In [6]:
#cambiar nombre de las columnas 
df_premier.rename(columns={'Date':'date',
                           'HomeTeam':'home_team',
                           'AwayTeam':'away_team',
                           'FTHG':'home_goals',# inplace modifica el dataframe original
                           'FTAG':'away_goals',},inplace=True)

In [8]:
df_premier

,Div,date,Time,home_team,away_team,home_goals,away_goals,FTR,HTHG,HTAG,...,AvgC<2.5,AHCh,B365CAHH,B365CAHA,PCAHH,PCAHA,MaxCAHH,MaxCAHA,AvgCAHH,AvgCAHA
0,E0,12/09/2020,12:30,Fulham,Arsenal,0,3,A,0,1,...,1.84,0.75,2.01,1.89,2.02,1.91,2.13,1.92,2.02,1.87
1,E0,12/09/2020,15:00,Crystal Palace,Southampton,1,0,H,1,0,...,1.70,0.25,1.78,2.13,1.79,2.17,1.85,2.18,1.79,2.12
2,E0,12/09/2020,17:30,Liverpool,Leeds,4,3,H,3,2,...,2.62,-1.50,1.85,2.05,1.85,2.08,1.90,2.16,1.84,2.04
3,E0,12/09/2020,20:00,West Ham,Newcastle,0,2,A,0,0,...,1.92,-0.50,2.03,1.87,2.04,1.88,2.09,1.91,2.02,1.86
4,E0,13/09/2020,14:00,West Brom,Leicester,0,3,A,0,0,...,1.73,0.25,1.92,1.98,1.93,1.99,1.95,2.01,1.91,1.97
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
375,E0,23/05/2021,16:00,Liverpool,Crystal Palace,2,0,H,1,0,...,3.49,-2.25,1.86,2.04,1.88,2.03,1.98,2.14,1.88,2.00
376,E0,23/05/2021,16:00,Man City,Everton,5,0,H,2,0,...,2.77,-1.75,2.01,1.89,1.99,1.89,2.20,2.00,2.03,1.85
377,E0,23/05/2021,16:00,Sheffield United,Burnley,1,0,H,1,0,...,2.05,0.00,2.04,1.86,2.05,1.86,2.17,1.90,2.03,1.84
378,E0,23/05/2021,16:00,West Ham,Southampton,3,0,H,2,0,...,2.14,-0.75,2.00,1.90,2.02,1.91,2.06,2.01,1.99,1.89
379,E0,23/05/2021,16:00,Wolves,Man United,1,2,A,1,2,...,1.62,-0.25,2.04,1.86,2.10,1.84,2.10,1.94,2.00,1.88

In [ ]:
#LEER .CSV DE MULTIPLES URLS CON PANDAS

#https://www.football-data.co.uk/mmz4281/2122/E0.csv
#https://www.football-data.co.uk/mmz4281/2122/E1.csv
#https://www.football-data.co.uk/mmz4281/2122/E2.csv
#https://www.football-data.co.uk/mmz4281/2122/E3.csv
#https://www.football-data.co.uk/mmz4281/2122/EC.csv

#LINK: root + season + league

In [11]:
#ESTRUCTURA DE UN LINK

"https://www.football-data.co.uk/mmz4281/"+"2122"+"/"+"E0"+".csv"

'https://www.football-data.co.uk/mmz4281/2122/E0.csv'

In [23]:
#crear una varible raiz

root="https://www.football-data.co.uk/mmz4281/"

In [15]:
#crear una lista de ligas

leagues=['E0','E1','E2','E3','EC']

frames=[]

#hacer loop en la lista, leer multiples csv y adjuntarlo 
for league in leagues:
    df=pd.read_csv(root+'2122'+'/'+league+'.csv',encoding='unicode_escape')
    frames.append(df)#con esto se va almacenar todos los dataframes, q estan en iteracion

In [18]:
#tamanio de los frames
len(frames)#ver el tamanio del frame

5

In [22]:
#mostrar el 1er ,2do y 3er elemento 

frames[4]

,Div,Date,Time,HomeTeam,AwayTeam,FTHG,FTAG,FTR,HTHG,HTAG,...,AvgC<2.5,AHCh,B365CAHH,B365CAHA,PCAHH,PCAHA,MaxCAHH,MaxCAHA,AvgCAHH,AvgCAHA
0,EC,21/08/2021,15:00,Aldershot,Chesterfield,0,2,A,0,0,...,1.93,0.50,1.98,1.83,2.03,1.83,2.05,1.90,1.97,1.80
1,EC,21/08/2021,15:00,Barnet,Notts County,0,5,A,0,0,...,2.06,0.75,1.88,1.93,1.90,1.95,2.00,1.95,1.90,1.88
2,EC,21/08/2021,15:00,Halifax,Maidenhead,1,2,A,1,0,...,1.94,-0.50,1.93,1.88,1.99,1.87,2.03,1.93,1.94,1.84
3,EC,21/08/2021,15:00,Kings Lynn,Southend,0,1,A,0,1,...,1.91,0.25,1.75,2.05,1.81,2.06,1.90,2.11,1.76,2.02
4,EC,21/08/2021,15:00,Solihull,Wrexham,2,2,D,1,2,...,1.85,0.00,2.05,1.75,1.93,1.92,2.05,1.98,1.92,1.86
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
501,EC,15/05/2022,15:00,Dover Athletic,Weymouth,1,2,A,0,1,...,2.50,0.25,1.88,1.93,1.87,1.98,1.90,1.98,1.85,1.93
502,EC,15/05/2022,15:00,Eastleigh,Grimsby,4,4,D,0,2,...,2.30,0.50,1.88,1.93,1.88,1.98,1.95,1.98,1.87,1.90
503,EC,15/05/2022,15:00,Maidenhead,Notts County,0,1,A,0,0,...,2.42,0.50,1.95,1.85,2.03,1.83,2.03,1.96,1.92,1.87
504,EC,15/05/2022,15:00,Southend,Torquay,1,1,D,0,1,...,2.01,-0.25,2.02,1.77,2.03,1.83,2.07,1.85,2.00,1.80
505,EC,15/05/2022,15:00,Stockport,Halifax,2,0,H,1,0,...,1.97,-0.75,1.80,2.00,1.79,2.08,1.93,2.08,1.84,1.95

In [ ]:
#esto de aca me va a permitir obtener las temporadas
# 6 temporadas 
for season in range(15,21):
    print(str(season)+str(season+1))

1516
1617
1718
1819
1920
2021

In [27]:
#df['season']=season esta es otra manera de inserta nueva columna, pero lo insertaria al final del dataset

# 3 ligas 
leagues=['E1','E2','E3']

frames=[]


#hacer looop a un rango de temporadas e insertar una nueva columna
for league in leagues:
    for season in range(15,21):#extraer la temporada 15 hasta la temporada 20

        df=pd.read_csv(root+str(season)+str(season+1)+'/'+league+'.csv')
        #crear una nueva columna que identifique a que temporada pertenece cada archivo .csv
        df.insert(1,'season',season)
        frames.append(df)

In [30]:
#total de frames 6 temporadas x 3 ligas 

len(frames)

18

In [34]:
#mostrar 1er y ultimo elemento (columan season fue creada )

frames[17]

,Div,season,Date,Time,HomeTeam,AwayTeam,FTHG,FTAG,FTR,HTHG,...,AvgC<2.5,AHCh,B365CAHH,B365CAHA,PCAHH,PCAHA,MaxCAHH,MaxCAHA,AvgCAHH,AvgCAHA
0,E3,20,12/09/2020,15:00,Barrow,Stevenage,1,1,D,1,...,1.76,-0.25,1.95,1.90,1.93,1.98,1.98,1.99,1.91,1.92
1,E3,20,12/09/2020,15:00,Bolton,Forest Green,0,1,A,0,...,1.79,-0.25,2.02,1.83,2.04,1.87,2.09,1.90,2.00,1.83
2,E3,20,12/09/2020,15:00,Bradford,Colchester,0,0,D,0,...,1.65,-0.25,2.07,1.72,2.11,1.82,2.20,1.82,2.09,1.76
3,E3,20,12/09/2020,15:00,Cambridge,Carlisle,3,0,H,2,...,1.70,-0.25,1.98,1.88,2.02,1.88,2.04,1.90,1.99,1.84
4,E3,20,12/09/2020,15:00,Cheltenham,Morecambe,1,2,A,1,...,1.75,-0.50,1.83,2.02,1.87,2.04,1.88,2.09,1.83,2.00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
547,E3,20,08/05/2021,15:00,Port Vale,Mansfield,0,3,A,0,...,1.84,0.25,1.90,1.95,1.89,2.00,1.95,2.07,1.85,1.97
548,E3,20,08/05/2021,15:00,Scunthorpe,Stevenage,0,1,A,0,...,1.73,0.50,1.80,2.05,1.84,2.06,1.87,2.14,1.77,2.07
549,E3,20,08/05/2021,15:00,Southend,Newport County,1,1,D,1,...,1.44,0.50,1.93,1.93,1.94,1.94,1.97,1.97,1.91,1.91
550,E3,20,08/05/2021,15:00,Tranmere,Colchester,0,0,D,0,...,1.59,-0.75,2.05,1.80,2.05,1.85,2.08,1.89,2.01,1.82
551,E3,20,08/05/2021,16:00,Salford,Leyton Orient,3,0,H,1,...,1.87,-1.00,1.98,1.88,1.99,1.90,2.01,1.96,1.96,1.86

In [2]:
#Crear un dicciionario con nombre original de liga como llave 

dic_countries={'Spanish La liga ':'SP1','Spanish Segunda Division':'SP2','German Bundesliga':'D1','English Premier League':'E0','English League 1':'E2','English League 2':'E3',}

In [7]:
#OBTENER UN ELEMENTO DEL DICCIONARIO
dic_countries['Spanish La liga ']

'SP1'

In [15]:
#MOSTRAR LA LLAVE
print('LLAVE ')
for league in dic_countries:
    print(league)
    
print("=====================================")
    
#MOSTRAR EL VALOR 
print('VALOR')
for league in dic_countries:
    print(dic_countries[league])

LLAVE
Spanish La liga
Spanish Segunda Division
German Bundesliga
English Premier League
English League 1
English League 2
=====================================
VALOR
SP1
SP2
D1
E0
E2
E3

In [25]:
#AQUI SE OBTENDRA UN DATAFRAME POR CADA LIGA Y ESE DATAFRAME VA A OBTENER LA DATA DE 5 O 6 TEMPORADAS

dict_historical_data={}


#hacer loop sobre llaves de diccionario
for league in dic_countries:
    frames=[]
    for season in range(15,21):#extraer la temporada 15 hasta la temporada 20

        df=pd.read_csv(root+str(season)+str(season+1)+'/'+dic_countries[league]+'.csv')
        #crear una nueva columna que identifique a que temporada pertenece cada archivo .csv
        df.insert(1,'season',season)
        frames.append(df)
    df_concat=pd.concat(frames)
    dict_historical_data[league]=df_concat

In [29]:
#MOSTRAR DATAFRAME DENTRO DE dict_historical_data

#dict_historical_data.keys()

dict_historical_data['English Premier League']

,Div,season,Date,HomeTeam,AwayTeam,FTHG,FTAG,FTR,HTHG,HTAG,...,AvgC<2.5,AHCh,B365CAHH,B365CAHA,PCAHH,PCAHA,MaxCAHH,MaxCAHA,AvgCAHH,AvgCAHA
0,E0,15,08/08/2015,Bournemouth,Aston Villa,0,1,A,0,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,E0,15,08/08/2015,Chelsea,Swansea,2,2,D,2,1,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,E0,15,08/08/2015,Everton,Watford,2,2,D,0,1,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,E0,15,08/08/2015,Leicester,Sunderland,4,2,H,3,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,E0,15,08/08/2015,Man United,Tottenham,1,0,H,1,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
375,E0,20,23/05/2021,Liverpool,Crystal Palace,2,0,H,1,0,...,3.49,-2.25,1.86,2.04,1.88,2.03,1.98,2.14,1.88,2.00
376,E0,20,23/05/2021,Man City,Everton,5,0,H,2,0,...,2.77,-1.75,2.01,1.89,1.99,1.89,2.20,2.00,2.03,1.85
377,E0,20,23/05/2021,Sheffield United,Burnley,1,0,H,1,0,...,2.05,0.00,2.04,1.86,2.05,1.86,2.17,1.90,2.03,1.84
378,E0,20,23/05/2021,West Ham,Southampton,3,0,H,2,0,...,2.14,-0.75,2.00,1.90,2.02,1.91,2.06,2.01,1.99,1.89
379,E0,20,23/05/2021,Wolves,Man United,1,2,A,1,2,...,1.62,-0.25,2.04,1.86,2.10,1.84,2.10,1.94,2.00,1.88